<?php
return [
    'SignupSmsCacheValidateTime' => 300,
    'SmsTimeout' => 240,
    'MobileRedisKeyPrefix' => 'guanjiasms_',
    'ErrCode' => array(
        'SUCCESS'   => 0,
        'PARAM_ERROR' => 1,
        'UNKNOWN_ERROR' => 2,
        'VERIFYCODE_ERROR' => 3,
        'VERIFYCODE_TIMEOUT' => 4,
        'SIGNUP_FAIL' => 5,
        'LOGIN_FAIL' => 6,
        'MOBILE_FAIL' => 7,
        'UPLOAD_IMG_FAIL' => 8,
        'SCHOOL_AUTH_FAIL' => 9,
        'DEGREE_AUTH_FAIL' => 10,
        'DEGREE_IS_EMPTY' => 11,
        'THIRD_LOGIN_CHECK_FAIL' => 12,
        'THIRD_LOGIN_FAIL' => 13,
        'UN_REGISTER_USER' => 14,
        'BIND_MOBILE_FAIL' => 15,
        'SMS_REQUEST_TOO_MANY' => 16,
        'SMS_REQUEST_FAIL' => 17,
        'NAME_AUTH_FAIL' => 18,
        'ID_CARD_AUTH_FAIL' => 19,
        'NOT_AUTH_SUCCESS' => 20,
        'NOT_TALENT_INFO' => 21,
        'EMPTY_VCODE' => 22,
        'VCODE_ERROR' => 23,
        'RCODE_ERROR' => 24,
        'TALENT_LEVEL_NOT_MATCH_HOTEL' => 25,
    ),
    'ErrMsg' => array(
        'SUCCESS'   => '成功',
        'PARAM_ERROR' => '参数错误',
        'UNKNOWN_ERROR' => '',
        'VERIFYCODE_ERROR' => '短信验证码错误',
        'VERIFYCODE_TIMEOUT' => '短信验证码超时',
        'SIGNUP_FAIL' => '注册失败',
        'LOGIN_FAIL' => '登录失败',
        'MOBILE_FAIL' => '手机号码错误或手机号码已注册',
        'UPLOAD_IMG_FAIL' => '上传图片失败',
        'SCHOOL_AUTH_FAIL' => '学信网学校认证不通过',
        'DEGREE_AUTH_FAIL' => '学信网学位认证不通过',
        'DEGREE_IS_EMPTY' => '未提交学历信息',
        'THIRD_LOGIN_CHECK_FAIL' => '第三方登录校验失败',
        'THIRD_LOGIN_FAIL' => '登录失败',
        'UN_REGISTER_USER' => '用户未注册',
        'BIND_MOBILE_FAIL' => '该手机号已注册，请直接用手机号登录',
        'SMS_REQUEST_TOO_MANY' => '验证码请求过于频繁,请稍后再试',
        'SMS_REQUEST_FAIL' => '验证码请求失败，请稍后再试',
        'NAME_AUTH_FAIL' => '用户学信网姓名与用户提交的个人资料姓名不一致',
        'ID_CARD_AUTH_FAIL' => '用户身份证号错误，请核对',
        'NOT_AUTH_SUCCESS' => '用户未认证成功,请先认证或查看自己的认证状态',
        'NOT_TALENT_INFO' => '你没有提交个人详细信息、教育、学历信息, 请先到个人中心提交',
        'EMPTY_VCODE' => '学信网学历或学籍在线验证码为空,请到学信网查询填写',
        'VCODE_ERROR' => '学信网在线学籍验证码错误',
        'RCODE_ERROR' => '学信网在线学历验证码错误',
        'TALENT_LEVEL_NOT_MATCH_HOTEL' => '你不是该酒店适用的人才级别,请选择其他酒店',
    ),
    'policy.default' => array(
        'pn' => 0,
        'rn' => 10,
        'type' => 1,
    ),
];
